165

# Инструкция)) 
# "#" - это заголовок h1

## "##" - это h2
***
"***" - это полосока
***
![alt text](<Снимок экрана 2024-09-10 230600.png>)
> ">" - цитата
>> ">>" - Цитата в цитате)
>> - "-" - список


1. ФЫВ

2. фывфы

<code>a = b + c  </code>

`a = b + c`

Я очень люблю Пиво .[Нажми на меня](https://github.com/egorkaw2w/AnimationAgain)

In [5]:
import pandas as pd
import numpy as np

In [9]:
city = {'Города': ['Москва','Воронеж','Нижний-новгород','Звенигород'],
        'Год основания':[1147,1586,1221,1152],
        'Численность':[140000000,10456000,10000000,15000]}
df_city = pd.DataFrame(city)
df_city

            Города  Год основания  Численность
0           Москва           1147    140000000
1          Воронеж           1586     10456000
2  Нижний-новгород           1221     10000000
3       Звенигород           1152        15000

In [11]:
df = pd.read_csv('dataset.csv')
df

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,13292,E.X. Troopers,PS3,2012.0,Shooter,Capcom,0.00,0.00,0.05,0.00,0.05
1,15041,Steins;Gate: Senkei Kousoku no Phonogram,X360,2013.0,Adventure,5pb,0.00,0.00,0.02,0.00,0.02
2,15717,This War of Mine,PS4,2016.0,Action,Deep Silver,0.00,0.01,0.00,0.00,0.02
3,14047,Kiniro no Corda 2 f,PSP,2009.0,Role-Playing,Tecmo Koei,0.00,0.00,0.04,0.00,0.04
4,5127,Turok: Rage Wars,N64,1999.0,Shooter,Acclaim Entertainment,0.30,0.06,0.00,0.00,0.37
...,...,...,...,...,...,...,...,...,...,...,...
548,12286,My Pet Chimp,DS,2010.0,Simulation,505 Games,0.06,0.00,0.00,0.00,0.06
549,10521,God Eater 2: Rage Burst,PS4,2015.0,Role-Playing,Namco Bandai Games,0.00,0.01,0.09,0.00,0.10
550,4981,Triple Play 97,PS,1996.0,Sports,Electronic Arts Victor,0.21,0.15,0.00,0.03,0.38
551,1157,Dragon Quest V: Hand of the Heavenly Bride,DS,2008.0,Role-Playing,Square Enix,0.19,0.02,1.36,0.02,1.60
552,10192,Tales of Phantasia (PS1 & PSP Versions),PSP,2006.0,Role-Playing,Namco Bandai Games,0.00,0.00,0.11,0.00,0.11

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 553 entries, 0 to 552
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Rank          553 non-null    int64
 1   Name          553 non-null    object
 2   Platform      553 non-null    object
 3   Year          542 non-null    float64
 4   Genre         553 non-null    object
 5   Publisher     549 non-null    object
 6   NA_Sales      553 non-null    float64
 7   EU_Sales      553 non-null    float64
 8   JP_Sales      553 non-null    float64
 9   Other_Sales   553 non-null    float64
 10  Global_Sales  553 non-null    float64
dtypes: float64(6), int64(1), object(4)
memory usage: 47.7+ KB

In [18]:
df.shape

(553, 11)

In [19]:
df.shape[0]

553

In [21]:
df.shape[1]

11

In [22]:
df.head(5)

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,13292,E.X. Troopers,PS3,2012.0,Shooter,Capcom,0.0,0.00,0.05,0.0,0.05
1,15041,Steins;Gate: Senkei Kousoku no Phonogram,X360,2013.0,Adventure,5pb,0.0,0.00,0.02,0.0,0.02
2,15717,This War of Mine,PS4,2016.0,Action,Deep Silver,0.0,0.01,0.00,0.0,0.02
3,14047,Kiniro no Corda 2 f,PSP,2009.0,Role-Playing,Tecmo Koei,0.0,0.00,0.04,0.0,0.04
4,5127,Turok: Rage Wars,N64,1999.0,Shooter,Acclaim Entertainment,0.3,0.06,0.00,0.0,0.37

In [23]:
df.tail(5)

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
548,12286,My Pet Chimp,DS,2010.0,Simulation,505 Games,0.06,0.00,0.00,0.00,0.06
549,10521,God Eater 2: Rage Burst,PS4,2015.0,Role-Playing,Namco Bandai Games,0.00,0.01,0.09,0.00,0.10
550,4981,Triple Play 97,PS,1996.0,Sports,Electronic Arts Victor,0.21,0.15,0.00,0.03,0.38
551,1157,Dragon Quest V: Hand of the Heavenly Bride,DS,2008.0,Role-Playing,Square Enix,0.19,0.02,1.36,0.02,1.60
552,10192,Tales of Phantasia (PS1 & PSP Versions),PSP,2006.0,Role-Playing,Namco Bandai Games,0.00,0.00,0.11,0.00,0.11

In [25]:
df.loc[18:30]

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
18,10822,The X-Factor,X360,2010.0,Misc,Deep Silver,0.00,0.08,0.00,0.01,0.09
19,15606,Tsuki no Hikari: Shizumeru Kane no Satsujin,PS2,2002.0,Adventure,Victor Interactive,0.00,0.00,0.02,0.00,0.02
20,13668,Little Busters! Converted Edition,PSP,2010.0,Adventure,Prototype,0.00,0.00,0.04,0.00,0.04
21,5989,WinBack: Covert Operations,PS2,2000.0,Shooter,Midas Interactive Entertainment,0.14,0.11,0.00,0.04,0.29
22,7420,WipeOut 3 The Game,X360,2012.0,Action,Activision,0.20,0.00,0.00,0.01,0.21
23,2123,Tom Clancy's Splinter Cell: Blacklist,PS3,2013.0,Action,Ubisoft,0.34,0.41,0.06,0.18,0.98
24,7680,Taiko Drum Master,PS2,2004.0,Misc,Namco Bandai Games,0.10,0.08,0.00,0.03,0.20
25,8919,Major League Baseball 2K8,PS2,2008.0,Sports,Bethesda Softworks,0.07,0.06,0.00,0.02,0.15
26,5219,Breath of Fire II,SNES,1994.0,Role-Playing,Laguna,0.00,0.00,0.36,0.00,0.36
27,2555,The Next Tetris,PS,1998.0,Puzzle,Atari,0.45,0.31,0.00,0.05,0.81
28,1054,Personal Trainer: Math,DS,2007.0,Puzzle,Nintendo,0.49,1.12,0.00,0.09,1.70
29,4847,The Urbz: Sims in the City,GC,2004.0,Simulation,Electronic Arts,0.24,0.14,0.00,0.02,0.40
30,16118,Brain Exercise With Dr. Kawashima,PC,2009.0,Puzzle,Namco Bandai Games,0.00,0.01,0.00,0.00,0.01

In [26]:
df.loc[10:30:5]

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
10,476,Devil May Cry,PS2,2001.0,Action,Capcom,1.36,0.86,0.64,0.13,2.99
15,5707,Crash Nitro Kart,XB,2003.0,Racing,Vivendi Games,0.24,0.07,0.00,0.01,0.31
20,13668,Little Busters! Converted Edition,PSP,2010.0,Adventure,Prototype,0.00,0.00,0.04,0.00,0.04
25,8919,Major League Baseball 2K8,PS2,2008.0,Sports,Bethesda Softworks,0.07,0.06,0.00,0.02,0.15
30,16118,Brain Exercise With Dr. Kawashima,PC,2009.0,Puzzle,Namco Bandai Games,0.00,0.01,0.00,0.00,0.01

In [28]:
df.iloc[10:30]

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
10,476,Devil May Cry,PS2,2001.0,Action,Capcom,1.36,0.86,0.64,0.13,2.99
11,1892,Endless Ocean,Wii,2007.0,Adventure,Nintendo,0.44,0.47,0.09,0.09,1.09
12,13535,Monster Trux Arenas: Special Edition,Wii,2007.0,Racing,Popcorn Arcade,0.04,0.00,0.00,0.00,0.04
13,12111,Ninja Warriors,SNES,1993.0,Action,Titus,0.00,0.00,0.07,0.00,0.07
14,14782,The Adventures of Lomax,PS,1996.0,Platform,Psygnosis,0.01,0.01,0.00,0.00,0.03
15,5707,Crash Nitro Kart,XB,2003.0,Racing,Vivendi Games,0.24,0.07,0.00,0.01,0.31
16,135,Red Dead Redemption,X360,2010.0,Action,Take-Two Interactive,3.70,1.97,0.09,0.57,6.34
17,11405,My English Coach: Para Hispanoparlantes,DS,2009.0,Misc,Ubisoft,0.08,0.00,0.00,0.01,0.08
18,10822,The X-Factor,X360,2010.0,Misc,Deep Silver,0.00,0.08,0.00,0.01,0.09
19,15606,Tsuki no Hikari: Shizumeru Kane no Satsujin,PS2,2002.0,Adventure,Victor Interactive,0.00,0.00,0.02,0.00,0.02
20,13668,Little Busters! Converted Edition,PSP,2010.0,Adventure,Prototype,0.00,0.00,0.04,0.00,0.04
21,5989,WinBack: Covert Operations,PS2,2000.0,Shooter,Midas Interactive Entertainment,0.14,0.11,0.00,0.04,0.29
22,7420,WipeOut 3 The Game,X360,2012.0,Action,Activision,0.20,0.00,0.00,0.01,0.21
23,2123,Tom Clancy's Splinter Cell: Blacklist,PS3,2013.0,Action,Ubisoft,0.34,0.41,0.06,0.18,0.98
24,7680,Taiko Drum Master,PS2,2004.0,Misc,Namco Bandai Games,0.10,0.08,0.00,0.03,0.20
25,8919,Major League Baseball 2K8,PS2,2008.0,Sports,Bethesda Softworks,0.07,0.06,0.00,0.02,0.15
26,5219,Breath of Fire II,SNES,1994.0,Role-Playing,Laguna,0.00,0.00,0.36,0.00,0.36
27,2555,The Next Tetris,PS,1998.0,Puzzle,Atari,0.45,0.31,0.00,0.05,0.81
28,1054,Personal Trainer: Math,DS,2007.0,Puzzle,Nintendo,0.49,1.12,0.00,0.09,1.70
29,4847,The Urbz: Sims in the City,GC,2004.0,Simulation,Electronic Arts,0.24,0.14,0.00,0.02,0.40

In [30]:
df.iloc[10:30,2:5]

   Platform    Year         Genre
10      PS2  2001.0        Action
11      Wii  2007.0     Adventure
12      Wii  2007.0        Racing
13     SNES  1993.0        Action
14       PS  1996.0      Platform
15       XB  2003.0        Racing
16     X360  2010.0        Action
17       DS  2009.0          Misc
18     X360  2010.0          Misc
19      PS2  2002.0     Adventure
20      PSP  2010.0     Adventure
21      PS2  2000.0       Shooter
22     X360  2012.0        Action
23      PS3  2013.0        Action
24      PS2  2004.0          Misc
25      PS2  2008.0        Sports
26     SNES  1994.0  Role-Playing
27       PS  1998.0        Puzzle
28       DS  2007.0        Puzzle
29       GC  2004.0    Simulation